# -*- coding: utf-8 -*-
"""Classement des produits NR / parapharma par rayon pharmacien.
Source de vérité unique, partagée par generate_marketing_mix.py et reclass_nr.py.
Ordre = priorité (1er mot-clé trouvé gagne). Mettre les rayons les plus spécifiques en tête.
Python 3.9.
"""
import re
import unicodedata

RAYONS = [
    ('Vaccins', ['VACCIN', 'TYPHIM', 'IXIARO', 'SHINGRIX', 'REPEVAX', 'PRIORIX', 'BOOSTRIX', 'ENGERIX', 'GARDASIL', 'VAXIGRIP', 'INFLUVAC', 'PNEUMOVAX', 'STAMARIL', 'RABIPUR', 'MENVEO', 'NIMENRIX', 'VARIVAX', 'HAVRIX', 'VAXNEUVANCE', 'SPIKEVAX', 'COMIRNATY', 'TETRAVAC', 'REVAXIS', 'INFANRIX', 'HEXYON']),
    ('Tests & autotests', ['AUTOTEST', 'AUTO-TEST', 'TEST ANTIG', 'TEST COVID', 'TEST GRIPPE', 'TROD ', 'TEST ANGINE']),
    ('Matériel & protection', ['MASQUE', 'FFP2', 'CHIRURGICAL', 'CHARLOTTE', 'GANT ', 'GANTS', 'BLOUSE', 'SURCHAUSS', 'TABLIER', 'CALOT', 'VISIERE']),
    ('Santé masculine & sexualité', ['TADALAFIL', 'SILDENAFIL', 'VARDENAFIL', 'AVANAFIL', 'VIAGRA', 'CIALIS', 'SPEDRA', 'ANDROGEL', 'TESTOSTERONE', 'PRESERVATIF']),
    ('Contraception & gynéco', ['OEDIEN', 'QLAIRA', 'SLINDA', 'ZOELY', 'EVRA', 'TRIAFEMI', 'OVUL', 'ABUFEN', 'CANDAZOL', 'CERAZETTE', 'SEASONIQUE', 'YAZ', 'DIANE 35', 'OPTIKINZY', 'MISOLFA', 'VABLYS', 'PROGIRON', 'PROGESTERONE', 'ISALIA', 'OPTILOVA', 'LEELOO', 'MINIDRIL', 'TRINORDIOL', 'JASMINELLE', 'OPTIMIZETTE', 'DESOGESTREL', 'LUTERAN', 'PROVAMES', 'LUBR INTIM', ' INTIM ', ' VAG ', 'GYNE', 'SAUGELLA', 'MONASENS', 'ESTRO']),
    ('Diabète & autosurveillance', ['BANDELETTE', 'ACCU-CHEK', 'ACCU CHEK', 'FREESTYLE', 'LANCETTE', 'AUTOPIQUEUR', 'ELECTRODE', 'GLYCEMIE', 'GLUCO', 'DEXTRO', 'AUTOPIQ', 'ONETOUCH', 'MOUNJARO', 'OZEMPIC', 'TRULICITY', 'VICTOZA', 'METFORMINE', 'STAGID', 'BD A MICROF', 'MICROFINE', 'MICROFIN', 'DEXCOM', 'CAPTEUR GLY', 'CONTOUR XT', 'CONTOUR PLUS', 'CONTOUR NEXT', 'CONTOUR BANDEL', 'NOVOFINE', 'NOVOTWIST', 'GLUCAGEN', 'INSUMAN', 'LANTUS', 'LEVEMIR', 'HUMALOG', 'NOVORAPID', 'LIBRE']),
    ('Minceur & surpoids', ['WEGOVY', 'SAXENDA', 'XENICAL', 'ORLISTAT', 'MINCEUR', 'ANACA3', 'XLS MEDICAL', 'XLS-MEDICAL']),
    ('Thyroïde & hormonal', ['TCAPS', 'LEVOTHYROX', 'LEVOTHYROXINE', 'L-THYROXINE', 'EUTHYRAL', 'CYNOMEL', 'THYROFIX', 'THYROID']),
    ('Ophtalmologie', ['COLLY', 'OPHT', 'OCUL', 'LARM', 'THEALOSE', 'VISMED', 'HYLO', 'OPTIVE', 'SKIACOL', 'NEOVIS', 'BLEPHA', 'SYSTANE', 'DACUDOSE', 'VITABACT', 'GTT OCUL', 'SOFTACORT', 'REFRESH', 'MONOPROST', 'CATIONORM', 'DESOMEDINE', 'ARTELAC', 'ELIXYA', 'CY DOS', 'CY FL', 'XAILIN', 'OFTAMAC', 'ILAST', 'MACULA', 'PAUP', 'VITAMINE A DULCIS']),
    ('Bouche & dentaire', ['STERADENT', 'PYRALVEX', 'AEQUASYAL', 'BAIN DE BOUCHE', 'BAIN BOUCHE', 'GINGIV', 'DENTAIRE', ' DENT ', 'APHTE', 'BUCCAL', ' BUC ', 'PAROEX', 'ELUDRIL', 'HEXTRIL', 'BORALINE', 'FIXODENT', 'DENTIFRICE', 'HYALUGEL']),
    ('ORL · Nez & gorge', ['NASAL', 'RHINO', 'NARIN', 'GORGE', 'SINUS', 'MOUCHE', 'DERINOX', 'STERIMAR', 'HUMER', 'PHYSIOMER', 'PASTILLE', 'NAS ', 'NAS.', 'NAS,', 'TOUX', 'COQUELUSEDAL', 'FERVEX', 'CALYPTOL', 'HUMEX', 'EXPECTO', 'RHINOFLUIMUCIL', 'STREPSIL', 'DRILL', 'MAXILASE', 'OROPER', 'HELICIDINE', 'TUSSIDANE', 'PRONTALGINE', 'EUPHON']),
    ('Allergies', ['ALLERG', 'AERIUS', 'XYZALL', 'CETIRIZINE', 'LORATADINE', 'DESLORATADINE', 'ZYRTEC', 'CLARITYNE', 'PERIACTINE', 'POLARAMINE', 'ATARAX', 'PHENERGAN', 'RUPAFIN', 'KESTIN']),
    ('Nausées & mal des transports', ['MERCALM', 'NAUSI', 'VOGALIB', 'VOGALENE', 'SCOPODERM', 'CARIBAN', 'NAUTAMINE', 'COCCULINE', 'MAL DES TRANSP', 'METOCLOPRAMIDE', 'DOMPERIDONE']),
    ('Antalgiques & douleur', ['DOLIPRANE', 'DAFALGAN', 'EFFERALGAN', 'IBUPRO', 'IBUFETUM', 'SPIFEN', 'NUROFEN', 'LAMALINE', 'IZALGI', 'ANTADYS', 'FLECTOR', 'PARACETAMOL', 'ASPIRINE', 'ASPEGIC', 'NIFLU', 'KETUM', 'VOLTAREN', 'CODOLIPRANE', 'LUMIRELAX', 'MYORELAX', 'DECONTRACT', 'OKIMUS', ' OKI ', 'IPRAFEINE', 'ACTRON', 'MIGRAINE', 'ANTIMIGR', 'HEXAQUINE', 'CRAMPE', 'BAUME DU TIGRE', 'SACETOL', 'CLARADOL', 'MIGPRIV', 'ZOMIG', 'IMIGRANE', 'BIPROFENID']),
    ('Digestif & transit', ['LAXAT', 'TRANSIT', 'NORMACOL', 'CONSTIP', 'GAVISCON', 'METEO', 'SPASFON', 'HEMORRO', 'DELIPROCT', 'SUPP', 'LAVEMENT', 'BEDELIX', 'KEAL', 'SPAGULAX', 'MOVICOL', 'FORLAX', 'MODANE', 'LANSOYL', 'X-PREP', 'XPREP', 'ESOXX', 'POLYSILANE', 'BETAINE', 'CHLORUMAGENE', 'CARBOSYLANE', 'SMECTA', 'IMODIUM', 'DEBRIDAT', 'MICROLAX', 'EDUCTYL', 'DULCOLAX', 'MAALOX', 'PHOSPHALUGEL', 'RENNIE', 'ULTRAPROCT', 'TITANOREINE', 'PSYLLIUM', 'SULFARLEM', 'RAPHANUS', 'REHYD', 'FANOLYTE', 'INEXIUM', 'PANTOPRAZOLE', 'OMEPRAZOLE', 'MOTILIUM', 'TIORFAN', 'ULCAR', 'QUESTRAN', 'EUPANTOL']),
    ('Pansements & cicatrisation', ['PANS', 'COMPRESS', 'MEPILEX', 'ALLEVYN', 'AQUACEL', 'JELONET', 'CONVAFOAM', 'HYDROCELL', 'HYDROFIBRE', 'ALGOSTERIL', 'URGO', 'MEPORE', 'TULLE', 'SPARADRAP', 'BIATAIN', 'BANDE ', 'IALUSET', 'EFFIDIA', 'COALGAN', 'OUATE', 'HEMOSTAT']),
    ('Dermatologie', ['CREME', 'POMM', 'BIAFINE', 'CICATRI', 'BRULURE', 'EMUL CUTA', 'DERMI', 'EPIDUO', 'SOOLANTRA', 'KERATO', 'CR TB', 'CR FL', 'BETADINE', 'VASELINE', 'CALENDULA', 'DUOFILM', 'VERRUE', 'ANTISEPT', 'DAKIN', 'BISEPTINE', 'HEXOMEDINE', 'CICALFATE', 'CETAVLON', 'DERMOVAL', 'DIPROSONE', 'LOCOID', 'MYCOSTER', 'AMYCOR', 'BAUME', 'POM TB', 'POM TUB', 'EOSINE', 'CHLORHEXIDINE', 'MITOSYL']),
    ('Circulation veineuse', ['VEIN', 'PHLEB', 'CONTENTION', 'VARICE', 'AETOXISCLEROL', 'VEINAMITOL', 'ESBERIVEN', 'ENDOTELON', 'DAFLON', 'GINKOR', 'CYCLO 3', 'CLIMAXOL', 'DIOSMINE']),
    ('Compléments & vitamines', ['VIT ', 'VITAM', 'MAGNES', 'MAGNE', 'FER ', 'ZINC', 'B12', 'OMEGA', 'OLIGO', 'BIOTINE', 'BEPANTHENE', 'PROBIO', 'TARDYFERON', 'NICOBION', 'PRINCI-B', 'BOP CPR', 'BEROCCA', 'BENERVA', 'BECILAN', 'SUPRADYN', 'AZINC', 'ALVITYL', 'FERROSTRANE', 'OLIGOSOL', 'FUMAFER', 'TIMOFEROL', 'GLUCONATE', 'ZYMAD', 'UVEDOSE', 'STEROGYL', 'CALCIUM']),
    ('Hygiène · Bébé · Sérum phy', ['SERUM PHY', 'PHYSIO', 'VERSOL', 'LAVAGE', 'BEBE', 'NETTOY', 'HYGIEN', 'SAVON', 'CHLOR NA', 'SOL IRR', 'PHYLARM', 'LINGETTE', 'LINIMENT', 'MUSTELA']),
    ('Sommeil · Stress', ['SOMMEIL', 'MELATON', 'EUPHYT', 'ANXEM', 'SERESTA', 'STRESAM', 'CARDIOCALM', 'LIBRAX', 'DONORMYL', 'SPASMINE', 'NOCTRAN', 'PASSIFLORE', 'VALERIANE', 'ZOLPIDEM', 'THERALENE', 'EUPHYTOSE', 'ETIFOXINE', 'MIANSERINE', 'LEXOMIL', 'XANAX', 'SYMPAVAGUE', 'ZOPICLONE']),
    ('Sevrage tabac', ['NICOR', 'NICOPATCH', 'NICOTINE', 'NIQUITIN', 'TABAC', 'NICOPASS', 'NICOTINELL']),
    ('Cardio & tension', ['PLAVIX', 'KARDEGIC', 'TAHOR', 'CRESTOR', 'AMLOR', 'COVERSYL', 'PREVISCAN', 'SINTROM', 'ELIQUIS', 'XARELTO', 'BISOPROLOL', 'RAMIPRIL', 'CARDENSIEL', 'LERCAN', 'APROVEL', 'TRIATEC']),
    ('Vétérinaire', ['VETO', ' CHIEN', ' CHAT', 'ANIMAL', 'MILBEMAX', 'FRONTLINE', 'ADVANTIX', 'BRAVECTO', 'NEXGARD']),
]


def classify_rayon(d):
    up = ' ' + unicodedata.normalize('NFKD', str(d or '')).encode('ascii', 'ignore').decode().upper() + ' '
    for lab, kws in RAYONS:
        for kw in kws:
            if kw in up:
                return lab
    return 'Autres produits NR'
